<a href="https://colab.research.google.com/github/Hoyadeath/practice_AI/blob/main/1_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Section 01. Intrododution to Numpy
## 1. Concept of Numply

In [6]:
# Jupiter notebook user
!pip install numpy

In [7]:
import numpy as np
print(np.__version__) # check Python libarary

1.25.2


##2. Numpy array

In [8]:
d=np.arange(12).reshape(3,4)
print(d,d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


###dtype

In [10]:
print(d.dtype)

int64


###ndim

In [ ]:
print(d.ndim)

2


###T

In [11]:
print(d.T) # transposed matrix

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


###size

In [14]:
print(d.size) # quantity of elements

12


###nbtypes

In [18]:
print(d.nbytes) # 64bit is 8byte, total 96byte(8*12)

96


### flat

In [19]:
d.flat=1
print(d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


##3. Create Numpy array
##by list

In [23]:
npa1=np.array([1, 2, 3])
print(type(npa1))

<class 'numpy.ndarray'>


In [24]:
list2=[[1, 2, 3],
 [4, 5, 6]]
print(type(list2))
npa2=np.array(list2) # Name the variable
print(type(npa2))

<class 'list'>
<class 'numpy.ndarray'>


###by dataframe

In [28]:
import pandas as pd
pd1=pd.DataFrame([1, 2, 3])
print(type(pd1))
np1=np.array(pd1)
print(type(np1))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [31]:
list2=[[1, 2, 3],
 [4, 5, 6]]
print(type(list2))
pd2=pd.DataFrame(list2)
print(type(pd2))
npa2=np.array(pd2)
print(type(npa2))
pd2

<class 'list'>
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


0  1  2
0  1  2  3
1  4  5  6

##4. n-dimensional Numpy array
###4-1. Create 1D Numpy array


In [32]:
import numpy as np
a=np.arange(3)
print(a, type(a), a.ndim, a.shape)

[0 1 2] <class 'numpy.ndarray'> 1 (3,)


####① set end value

In [33]:
a2=np.arange(4)
a2

array([0, 1, 2, 3])

#### ② set start and end values

In [35]:
a2=np.arange(2, 4)
print(a2, a2.shape)

[2 3] (2,)


####③ set start, ending, and increasing value

In [36]:
a3=np.arange(0, 5, 2)
print(a3, a3.shape)

[0 2 4] (3,)


###4-2. Create 2D Numpy array
####Create an array of 2 rows and 3 columns


In [ ]:
m=np.array([[0, 1, 2],
 [3, 4, 5]])
print(m, m.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [ ]:
m=np.array([np.arange(3), np.arange(3, 6)])
print(m, m.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


####Create an array of 3 rows and 2 columns

In [41]:
m=np.array([[0, 3],
 [1, 4],
 [2, 5]])
print(m, m.shape)
print(m.shape[0], m.shape[1])

[[0 3]
 [1 4]
 [2 5]] (3, 2)
3 2


In [ ]:
m=np.array([np.arange(0, 4, 3), np.arange(1, 5, 3),
np.arange(2, 6, 3)])
print(m, m.shape)

[[0 3]
 [1 4]
 [2 5]] (3, 2)


###4-3. Create 3D Numpy array

In [ ]:
m=np.array([[[0, 1, 2],
 [3, 4, 5]],
 [[0, 1, 2],
 [3, 4, 5]]])
print(m)
print(m.shape)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)


In [ ]:
m=np.array([[[0, 1],
 [2, 3]],
 [[4, 5],
 [6, 7]],
 [[8, 9],
 [10, 11]]])
print(m, m.shape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] (3, 2, 2)


In [45]:
m=np.array([[[0, 1, 2]],
 [[3, 4, 5]],
 [[0, 1, 2]],
 [[3, 4, 5]]])
print(m, m.shape)

[[[0 1 2]]

 [[3 4 5]]

 [[0 1 2]]

 [[3 4 5]]] (4, 1, 3)


###<Extra> Python range function & Numpy arange function

In [53]:
list=[1, 2, 3, 4, 5]
for i in list:
  print(i)

1
2
3
4
5


In [54]:
for i in range(1, 6):
  print(i)

1
2
3
4
5


In [55]:
for i in range(1, 6, 2):
  print(i)

1
3
5


In [56]:
arr=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [57]:
arr=np.arange(start=1, stop=11, step=1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr=np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr=np.arange(start=1, stop=10, step=2)
arr

array([1, 3, 5, 7, 9])

In [60]:
arr=np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

# Section 02. Practice of array
## 1. check and modify data type of array

In [64]:
import numpy as np
npa=np.array([0, 1, 2, 3, 4, 5])
print(npa, type(npa)) # Returns the datatype of an npa variable
print(npa.dtype) # Returns the datatype of npa element of Numpy array
npa # Show in array([]) format because it is a Numpy array

[0 1 2 3 4 5] <class 'numpy.ndarray'>
int64


array([0, 1, 2, 3, 4, 5])

In [66]:
npa1=np.array([0, 1, 2, 3.0, 4, 5])
print(npa1, npa1.dtype)

[0. 1. 2. 3. 4. 5.] float64


In [67]:
npa2=np.array([0, 1, 2, 3, 4, 5])
print(npa2, npa2.dtype)

[0 1 2 3 4 5] int64


## 2. Change form of array
### Change structure of array : reshape function

In [69]:
m1=np.arange(6)
print(m1)
print(m1.shape)

[0 1 2 3 4 5]
(6,)


In [70]:
m2=m1.reshape(6, 1)
print(m2, m2.shape) # Change 1 row & 6 columns to 6 rows & 1 column

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [71]:
m2=m1.reshape(2, 3)
print(m2, m2.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [72]:
m1=np.arange(12)
m3=m1.reshape(2, 2, 3)
print(m3, m3.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [ ]:
m1=np.arange(6)
print(m1, m1.shape)
m2=m1.reshape(-1, 2) # Rows are automatic and create 2 columns
print(m2, m2.shape)
m2=m1.reshape(-1, 3) # Rows are automatic and create 3 columns
print(m2, m2.shape)
m2=m1.reshape(-1, 1) # Rows are automatic and create 1 column
print(m2, m2.shape)

[0 1 2 3 4 5] (6,)
[[0 1]
 [2 3]
 [4 5]] (3, 2)
[[0 1 2]
 [3 4 5]] (2, 3)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [77]:
m1=np.arange(6)
m3=m1.reshape(-1, 2, 3)
print(m3, m3.shape)
m3=m1.reshape(-1, 3, 2) # Heights automatic and create 3 rows and 2 columns
print(m3,m3.shape)
m3=m1.reshape(2, 3, -1) # Columns are automatic and create 2 heights and 3 rows
print(m3, m3.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3)
[[[0 1]
  [2 3]
  [4 5]]] (1, 3, 2)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


###Flatten a multidimensional array into a one-dimensional array: flatten function

In [78]:
a=np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
f=a.flatten()
print(f, f.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


###Change direction of array

In [80]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
print(a[::-1]) # Reverse the order of the rows

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a[:,::-1]) # Reverse the order of the columns

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a[::-1,::-1]) # Reverse the order of the rows and columns

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [ ]:
t=a.transpose()
print(a, a.shape) # a has 3 rows and 4 columns
print(t, t.shape) # t changes a to 4 rows and 3 columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] (4, 3)


In [ ]:
print(a.T) # the same result as transpose() function

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


##3. Unite and divide array

In [103]:
a=np.arange(9).reshape(3, 3)
b=a*2
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [104]:
r=np.vstack((a, b))
print(r, r.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [85]:
c=np.row_stack((a, b))
print(c, c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [ ]:
x=np.concatenate((a, b), axis=0)
print(x, x.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


###Combine in the column direction


In [ ]:
r=np.hstack((a, b))
print(r, r.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [ ]:
c=np.column_stack((a, b))
print(c, c.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [ ]:
x=np.concatenate((a, b), axis=1)
print(x, x.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


###Split by row

In [108]:
a=np.arange(12).reshape(4, 3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [110]:
print(np.vsplit(a, 4))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [111]:
print(np.split(a, 4, axis=0))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [112]:
print(a[0:1], a[1:2], a[2:3], a[3:])

[[0 1 2]] [[3 4 5]] [[6 7 8]] [[ 9 10 11]]


###Split by column

In [113]:
a=np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [125]:
print(np.hsplit(a, 4))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [126]:
print(np.split(a, 4, axis=1))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


#Section 03. Indexing and slicing of array
##1. Indexing and slicing of 1D array

In [127]:
d=np.arange(6)
print(d, d.shape)

[0 1 2 3 4 5] (6,)


In [129]:
# Indexing of 1D array
print(d[0], d[1], d[2], d[-1], d[-2])

0 1 2 5 4


In [ ]:
# Slicing of 1D array
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])
d[0]=10 # Change the value of element
print(d)

[2] [0 1 2 3 4 5] [0 1 2 3 4]
[0 2 4] [5 4 3 2 1 0]
[10  1  2  3  4  5]


##2. Indexing and slicing of 2D array


In [141]:
d=np.arange(12).reshape(3, 4)
print(d, d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [142]:
# Indexing of 2D array
print(d[0][0]) # indexing row 0 column 0
print(d[0,0])  # indexing row 0 column 0
print(d[2,1])

0
0
9


In [143]:
# Slicing of 2D array
print(d[0]) #  Slicing only row 0
print(d[0,:]) #  Slicing all columns of row 0
print(d[:,:-1]) #  Slicing all columns and rows except the end column
print(d[::2,::2]) # Slicing full rows and columns at intervals of two rows and two columns

[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]


In [144]:
d[0]=20 # change all elements of row 0 to 20
print(d)

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [145]:
d[::2,::3]=30 # Change the sliced element values at once
print(d[::2,::3])
print(d)

[[30 30]
 [30 30]]
[[30 20 20 30]
 [ 4  5  6  7]
 [30  9 10 30]]


In [ ]:
d[:,:]=-1 # Change all element values at once
print(d)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


##3. Indexing and slicing of 3D array

In [152]:
d=np.arange(12).reshape(2, 2, 3)
print(d, d.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [153]:
# Indexing of 3D array
print(d[0][0][0]) # indexing height 0 row 0 column 0
print(d[0, 0, 0]) # indexing height 0 row 0 column 0
print(d[0, 1, 2]) # indexing height 0 row 1 column 2

0
0
5


In [154]:
# Slicing of 3D array
print(d[:,:-1,:-1])

[[[0 1]]

 [[6 7]]]


In [156]:
print(d[:,1:,1:])

[[[ 4  5]]

 [[10 11]]]


In [164]:
print(d[:,:,-1])
print(d[:,:,-1].shape)

[[ 2  5]
 [ 8 11]]
(2, 2)


In [165]:
print(d[:,-1,-1])
print(d[:,-1,-1].shape)

print(d[-1,-1,-1])
print(d[-1,-1,-1].shape)

[ 5 11]
(2,)
11
()


In [166]:
a=np.arange(12)
print(a, a.shape)
print(a[0]) # scala
print(a[0:1]) # ndarray

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0
[0]


##4. Bool indexing

In [ ]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [ ]:
print(a>2)

[False False  True  True  True  True]


In [ ]:
print(a[a>2])

[3 4 5 6]


##5. Condition Filter

In [169]:
a=np.array([1, 2, 3, 4, 5, 6])
result=a>2
result

array([False, False,  True,  True,  True,  True])

In [170]:
a[a>2]

array([3, 4, 5, 6])

In [171]:
a[a!=3]

array([1, 2, 4, 5, 6])

In [173]:
print(a[(a>2) & (a<6)]) # Extract only elements greater than 2 and less than 6
print(a[a % 2==0]) # Extract only elements whose remainder is 0 divided by 2
print(a[a<a.mean( )]) # Extract only values less than average

[3 4 5]
[2 4 6]
[1 2 3]


In [174]:
print(a[True])
print(a[False])

[[1 2 3 4 5 6]]
[]


#Section 04. Sort of Numpy arrays
##1 Basic sort : sort function

In [175]:
a=np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
print(a, a.shape)
r=np.sort(a)  # Sort in ascending order without changing the source
print(r, a)

[2 8 9 7 3 1 4 5 6] (9,)
[1 2 3 4 5 6 7 8 9] [2 8 9 7 3 1 4 5 6]


In [176]:
# Sort in ascending order
a.sort()
print(a)

[1 2 3 4 5 6 7 8 9]


In [177]:
# Sort in descending order
r=np.sort(a)[::-1]
print(r)

[9 8 7 6 5 4 3 2 1]


##2. Index return sort: argsort function

In [187]:
a=np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
print(a, a.shape)

[2 8 9 7 3 1 4 5 6] (9,)


In [179]:
np.argsort(a)

array([5, 0, 4, 6, 7, 8, 3, 1, 2])

In [188]:
sort_index=np.argsort(a)
print(sort_index)

[5 0 4 6 7 8 3 1 2]



##3. Sort of 2D arrays


In [181]:
arr2d=np.array([[5, 6, 7, 8],
 [4, 3, 2, 1],
 [10, 9, 12, 11]])
print(arr2d)
print(arr2d.shape)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
(3, 4)


In [182]:
# Sort elements in the same row in the column direction
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [183]:
# Sort elements in the same column in the row direction
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [189]:
# Sort the same row in the column direction
print(arr2d)
print(np.sort(arr2d))
np.argsort(arr2d, axis=1)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

In [ ]:
# Sort the same column in row direction
print(arr2d)
print(np.sort(arr2d, axis=0))
np.argsort(arr2d, axis=0)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)

#Section 05. Computation of Numpy arrays
## 1. Computation of Numpy arrays
### Computation of elements in an array


In [190]:
# Sum elements in the same array
import numpy as np
a=np.array([[1, 2, 3],
 [4, 5, 6]])
np.sum(a, axis=0), np.sum(a, axis=1)

(array([5, 7, 9]), array([ 6, 15]))

In [191]:
a.sum()

21

###Arithmetics of arrays and constants

In [192]:
a=np.array([[1, 2, 3],
 [4, 5, 6]])
b=2
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [ ]:
A=np.arange(1, 13).reshape(3, 4)
print(A+10)
print(A-10)
print(A*10)
print(A/10)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[[-9 -8 -7 -6]
 [-5 -4 -3 -2]
 [-1  0  1  2]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]


In [196]:
A=np.arange(1, 13).reshape(3, 4)
A-1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Computations between elements of arrays

In [ ]:
a=np.array([[1, 2, 3],
 [4, 5, 6]])
b=np.array([1, 2, 3]) # b=np.array([[1, 2, 3]]) is possible too
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


###The difference between multiplication between arrays and matrix multiplication



In [193]:
a=np.array([[1, 2],
 [3, 4]])
b=np.array([[1, 2],
 [1, 2]])
print(a*b)
print(a.dot(b))

[[1 4]
 [3 8]]
[[ 3  6]
 [ 7 14]]


##2. Broadcasting

In [ ]:
A=np.array([[1, 2],
 [3, 4]])
B=np.array([1, 2])
A+B

array([[2, 4],
       [4, 6]])

In [ ]:
A=np.array([[1, 2, 3],
 [4, 5, 6]])
B=np.array([2])
A+B

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
A=np.array([[1, 2, 3],
 [4, 5, 6]])
B=np.array([[2],
 [4]])
A+B

array([[ 3,  4,  5],
       [ 8,  9, 10]])